CATEGORY_CHOICES = (
    ('Arts'), ('Arts'),
    ('Arts :: Design'), ('Arts :: Design'),
    ('Arts :: Fashion &amp; Beauty'), ('Arts :: Fashion &amp; Beauty'),
    ('Arts :: Food'), ('Arts :: Food'),
    ('Arts :: Books'), ('Arts :: Books'),
    ('Arts :: Performing Arts'), ('Arts :: Performing Arts'),
    ('Arts :: Visual Arts'), ('Arts :: Visual Arts'),
    ('Business'), ('Business'),
    ('Business :: Careers'), ('Business :: Careers'),
    ('Business :: Entrepreneurship'), ('Business :: Entrepreneurship'),
    ('Business :: Investing'), ('Business :: Investing'),
    ('Business :: Management'), ('Business :: Management'),
    ('Business :: Marketing'), ('Business :: Marketing'),
    ('Business :: Non-Profit'), ('Business :: Non-Profit'),
    ('Comedy'), ('Comedy'),
    ('Comedy :: Comedy Interviews'), ('Comedy :: Comedy Interviews'),
    ('Comedy :: Improv'), ('Comedy :: Improv'),
    ('Comedy :: Stand-Up'), ('Comedy :: Stand-Up'),
    ('Education'), ('Education'),
    ('Education :: Courses'), ('Education :: Courses'),
    ('Education :: How To'), ('Education :: How To'),
    ('Education :: Language Learning'), ('Education :: Language Learning'),
    ('Education :: Self-Improvement'), ('Education :: Self-Improvement'),
    ('Fiction'), ('Fiction'),
    ('Fiction :: Comedy Fiction'), ('Fiction :: Comedy Fiction'),
    ('Fiction :: Drama'), ('Fiction :: Drama'),
    ('Fiction :: Science Fiction'), ('Fiction :: Science Fiction'),
    ('Leisure'), ('Leisure'),
    ('Leisure :: Animation &amp; Manga'), ('Leisure :: Animation &amp; Manga'),
    ('Leisure :: Automotive'), ('Leisure :: Automotive'),
    ('Leisure :: Aviation'), ('Leisure :: Aviation'),
    ('Leisure :: Crafts'), ('Leisure :: Crafts'),
    ('Leisure :: Games'), ('Leisure :: Games'),
    ('Leisure :: Hobbies'), ('Leisure :: Hobbies'),
    ('Leisure :: Home &amp; Garden'), ('Leisure :: Home &amp; Garden'),
    ('Leisure :: Video Games'), ('Leisure :: Video Games'),
    ('Government'), ('Government'),
    ('Health &amp; Fitness'), ('Health &amp; Fitness'),
    ('Health &amp; Fitness :: Alternative Health'), ('Health &amp; Fitness :: Alternative Health'),
    ('Health &amp; Fitness :: Fitness'), ('Health &amp; Fitness :: Fitness'),
    ('Health &amp; Fitness :: Medicine'), ('Health &amp; Fitness :: Medicine'),
    ('Health &amp; Fitness :: Mental Health'), ('Health &amp; Fitness :: Mental Health'),
    ('Health &amp; Fitness :: Nutrition'), ('Health &amp; Fitness :: Nutrition'),
    ('Health &amp; Fitness :: Sexuality'), ('Health &amp; Fitness :: Sexuality'),
    ('History'), ('History'),
    ('Kids &amp; Family'), ('Kids &amp; Family'),
    ('Kids &amp; Family :: Education for Kids'), ('Kids &amp; Family :: Education for Kids'),
    ('Kids &amp; Family :: Parenting'), ('Kids &amp; Family :: Parenting'),
    ('Kids &amp; Family :: Pets &amp; Animals'), ('Kids &amp; Family :: Pets &amp; Animals'),
    ('Kids &amp; Family :: Stories for Kids'), ('Kids &amp; Family :: Stories for Kids'),
    ('Music'), ('Music'),
    ('Music :: Music Commentary'), ('Music :: Music Commentary'),
    ('Music :: Music History'), ('Music :: Music History'),
    ('Music :: Music Interviews'), ('Music :: Music Interviews'),
    ('News'), ('News'),
    ('News :: Business News'), ('News :: Business News'),
    ('News :: Daily News'), ('News :: Daily News'),
    ('News :: Entertainment News'), ('News :: Entertainment News'),
    ('News :: News Commentary'), ('News :: News Commentary'),
    ('News :: Politics'), ('News :: Politics'),
    ('News :: Sports News'), ('News :: Sports News'),
    ('News :: Tech News'), ('News :: Tech News'),
    ('Religion &amp; Spirituality'), ('Religion &amp; Spirituality'),
    ('Religion &amp; Spirituality :: Buddhism'), ('Religion &amp; Spirituality :: Buddhism'),
    ('Religion &amp; Spirituality :: Christianity'), ('Religion &amp; Spirituality :: Christianity'),
    ('Religion &amp; Spirituality :: Hinduism'), ('Religion &amp; Spirituality :: Hinduism'),
    ('Religion &amp; Spirituality :: Islam'), ('Religion &amp; Spirituality :: Islam'),
    ('Religion &amp; Spirituality :: Judaism'), ('Religion &amp; Spirituality :: Judaism'),
    ('Religion &amp; Spirituality :: Religion'), ('Religion &amp; Spirituality :: Religion'),
    ('Religion &amp; Spirituality :: Spirituality'), ('Religion &amp; Spirituality :: Spirituality'),
    ('Science'), ('Science'),
    ('Science :: Astronomy'), ('Science :: Astronomy'),
    ('Science :: Chemistry'), ('Science :: Chemistry'),
    ('Science :: Earth Sciences'), ('Science :: Earth Sciences'),
    ('Science :: Life Sciences'), ('Science :: Life Sciences'),
    ('Science :: Mathematics'), ('Science :: Mathematics'),
    ('Science :: Natural Sciences'), ('Science :: Natural Sciences'),
    ('Science :: Nature'), ('Science :: Nature'),
    ('Science :: Physics'), ('Science :: Physics'),
    ('Science :: Social Sciences'), ('Science :: Social Sciences'),
    ('Society &amp; Culture'), ('Society &amp; Culture'),
    ('Society &amp; Culture :: Documentary'), ('Society &amp; Culture :: Documentary'),
    ('Society &amp; Culture :: Personal Journals'), ('Society &amp; Culture :: Personal Journals'),
    ('Society &amp; Culture :: Philosophy'), ('Society &amp; Culture :: Philosophy'),
    ('Society &amp; Culture :: Places &amp; Travel'), ('Society &amp; Culture :: Places &amp; Travel'),
    ('Society &amp; Culture :: Relationships'), ('Society &amp; Culture :: Relationships'),
    ('Sports'), ('Sports'),
    ('Sports :: Baseball'), ('Sports :: Baseball'),
    ('Sports :: Basketball'), ('Sports :: Basketball'),
    ('Sports :: Cricket'), ('Sports :: Cricket'),
    ('Sports :: Fantasy Sports'), ('Sports :: Fantasy Sports'),
    ('Sports :: Football'), ('Sports :: Football'),
    ('Sports :: Golf'), ('Sports :: Golf'),
    ('Sports :: Hockey'), ('Sports :: Hockey'),
    ('Sports :: Rugby'), ('Sports :: Rugby'),
    ('Sports :: Running'), ('Sports :: Running'),
    ('Sports :: Soccer'), ('Sports :: Soccer'),
    ('Sports :: Swimming'), ('Sports :: Swimming'),
    ('Sports :: Tennis'), ('Sports :: Tennis'),
    ('Sports :: Volleyball'), ('Sports :: Volleyball'),
    ('Sports :: Wilderness'), ('Sports :: Wilderness'),
    ('Sports :: Wrestling'), ('Sports :: Wrestling'),
    ('Technology'), ('Technology'),
    ('True Crime'), ('True Crime'),
    ('TV &amp; Film'), ('TV &amp; Film'),
    ('TV &amp; Film :: After Shows'), ('TV &amp; Film :: After Shows'),
    ('TV &amp; Film :: Film History'), ('TV &amp; Film :: Film History'),
    ('TV &amp; Film :: Film Interviews'), ('TV &amp; Film :: Film Interviews'),
    ('TV &amp; Film :: Film Reviews'), ('TV &amp; Film :: Film Reviews'),
    ('TV &amp; Film :: TV Reviews'), ('TV &amp; Film :: TV Reviews'),
)
