LANGUAGE_CHOICES = (
    ('en'), ('English'),
    ('es'), ('Spanish'),
    ('de'), ('German'),
    ('fr'), ('French'),
    ('af'), ('Afrikaans'),
    ('sq'), ('Albanian'),
    ('ar'), ('Arabic'),
    ('eu'), ('Basque'),
    ('be'), ('Belarusian'),
    ('bg'), ('Bulgarian'),
    ('ca'), ('Catalan'),
    ('zh-cn'), ('Chinese (Simplified)'),
    ('zh-tw'), ('Chinese (Traditional)'),
    ('hr'), ('Croatian'),
    ('cs'), ('Czech'),
    ('da'), ('Danish'),
    ('nl'), ('Dutch'),
    ('nl-be'), ('Dutch (Belgium)'),
    ('nl-nl'), ('Dutch (Netherlands)'),
    ('en-au'), ('English (Australia)'),
    ('en-bz'), ('English (Belize)'),
    ('en-ca'), ('English (Canada)'),
    ('en-ie'), ('English (Ireland)'),
    ('en-jm'), ('English (Jamaica)'),
    ('en-nz'), ('English (New Zealand)'),
    ('en-ph'), ('English (Phillipines)'),
    ('en-za'), ('English (South Africa)'),
    ('en-tt'), ('English (Trinidad)'),
    ('en-gb'), ('English (United Kingdom)'),
    ('en-us'), ('English (United States)'),
    ('en-zw'), ('English (Zimbabwe)'),
    ('et'), ('Estonian'),
    ('fo'), ('Faeroese'),
    ('fi'), ('Finnish'),
    ('fr-be'), ('French (Belgium)'),
    ('fr-ca'), ('French (Canada)'),
    ('fr-fr'), ('French (France)'),
    ('fr-lu'), ('French (Luxembourg)'),
    ('fr-mc'), ('French (Monaco)'),
    ('fr-ch'), ('French (Switzerland)'),
    ('gd'), ('Gaelic'),
    ('gl'), ('Galician'),
    ('de-at'), ('German (Austria)'),
    ('de-de'), ('German (Germany)'),
    ('de-li'), ('German (Liechtenstein)'),
    ('de-lu'), ('German (Luxembourg)'),
    ('de-ch'), ('German (Switzerland)'),
    ('el'), ('Greek'),
    ('haw'), ('Hawaiian'),
    ('he'), ('Hebrew'),
    ('hi'), ('Hindi'),
    ('hu'), ('Hungarian'),
    ('is'), ('Icelandic'),
    ('in'), ('Indonesian'),
    ('ga'), ('Irish'),
    ('it'), ('Italian'),
    ('it-it'), ('Italian (Italy)'),
    ('it-ch'), ('Italian (Switzerland)'),
    ('ja'), ('Japanese'),
    ('kn'), ('Kannada'),
    ('ko'), ('Korean'),
    ('lv'), ('Latvian'),
    ('lt'), ('Lithuanian'),
    ('mk'), ('Macedonian'),
    ('ms'), ('Malay'),
    ('ml'), ('Malayalam'),
    ('mr'), ('Marathi'),
    ('ne'), ('Nepali'),
    ('se'), ('Northern Sami'),
    ('no'), ('Norwegian'),
    ('fa'), ('Persian'),
    ('pl'), ('Polish'),
    ('pt'), ('Portuguese'),
    ('pt-br'), ('Portuguese (Brazil)'),
    ('pt-pt'), ('Portuguese (Portugal)'),
    ('pa'), ('Punjabi'),
    ('ro'), ('Romanian'),
    ('ro-mo'), ('Romanian (Moldova)'),
    ('ro-ro'), ('Romanian (Romania)'),
    ('ru'), ('Russian'),
    ('ru-mo'), ('Russian (Moldova)'),
    ('ru-ru'), ('Russian (Russia)'),
    ('sa'), ('Sanskrit'),
    ('sr'), ('Serbian'),
    ('sk'), ('Slovak'),
    ('sl'), ('Slovenian'),
    ('es-ar'), ('Spanish (Argentina)'),
    ('es-bo'), ('Spanish (Bolivia)'),
    ('es-cl'), ('Spanish (Chile)'),
    ('es-co'), ('Spanish (Colombia)'),
    ('es-cr'), ('Spanish (Costa Rica)'),
    ('es-do'), ('Spanish (Dominican Republic)'),
    ('es-ec'), ('Spanish (Ecuador)'),
    ('es-sv'), ('Spanish (El Salvador)'),
    ('es-gt'), ('Spanish (Guatemala)'),
    ('es-hn'), ('Spanish (Honduras)'),
    ('es-mx'), ('Spanish (Mexico)'),
    ('es-ni'), ('Spanish (Nicaragua)'),
    ('es-pa'), ('Spanish (Panama)'),
    ('es-py'), ('Spanish (Paraguay)'),
    ('es-pe'), ('Spanish (Peru)'),
    ('es-pr'), ('Spanish (Puerto Rico)'),
    ('es-es'), ('Spanish (Spain)'),
    ('es-uy'), ('Spanish (Uruguay)'),
    ('es-ve'), ('Spanish (Venezuela)'),
    ('sw'), ('Swahili'),
    ('sv'), ('Swedish'),
    ('sv-fi'), ('Swedish (Finland)'),
    ('sv-se'), ('Swedish (Sweden)'),
    ('ta'), ('Tamil'),
    ('te'), ('Telugu'),
    ('th'), ('Thai'),
    ('tr'), ('Turkish'),
    ('ur'), ('Urdu'),
    ('uk'), ('Ukranian'),
    ('vi'), ('Vietnamese'),
)