# Generated by Django 4.2.16 on 2024-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
