# Generated by Django 4.2.16 on 2024-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_podcast_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='explicit_content_warning',
            field=models.BooleanField(default=False),
        ),
    ]
