# Generated by Django 4.2.16 on 2024-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_alter_episode_alt_episode_url_alter_episode_artwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='publish_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
