# Generated by Django 4.2.16 on 2024-11-01 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_alter_episode_description_alter_episode_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='type',
        ),
    ]
