# Generated by Django 4.2.16 on 2024-11-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_alter_episode_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Trailer', 'Trailer'), ('Bonus', 'Bonus')], default='Normal'),
        ),
    ]
