# Generated by Django 4.2.16 on 2024-11-25 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0010_episode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='creator',
        ),
        migrations.AddField(
            model_name='episode',
            name='administrator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='podcast_administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='administrator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='podcast_shows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='artwork',
            field=models.CharField(blank=True, default='path/to/image/file', max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='copyright',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='owner_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
