# Generated by Django 4.2.16 on 2024-11-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0013_podcast_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
