# Generated by Django 4.2.16 on 2024-11-28 18:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0015_alter_episode_alt_episode_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='audiofile',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='audio'),
        ),
    ]
