# Generated by Django 4.2.16 on 2024-12-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0023_alter_episode_episode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
