# Generated by Django 4.2.16 on 2024-12-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0025_podcast_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('Normal', 'full'), ('Trailer', 'trailer'), ('Bonus', 'bonus')], default='Normal'),
        ),
    ]
