# Generated by Django 4.2.16 on 2024-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0026_alter_episode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='type',
            field=models.CharField(choices=[('full', 'Normal'), ('trailer', 'Trailer'), ('bonus', 'Bonus')], default='Normal'),
        ),
    ]
